create extension if not exists pgcrypto;
create table if not exists public.profiles(user_id uuid primary key references auth.users(id) on delete cascade,display_name text,account_type text not null default 'student' check(account_type in('student','coordinator','admin')),institutional_user boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.courses(id bigint generated by default as identity primary key,slug text unique not null,name text not null,description text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.semesters(id bigint generated by default as identity primary key,course_id bigint not null references public.courses(id) on delete cascade,name text not null,start_date date,end_date date,status text not null default 'planned' check(status in('planned','active','closed')),unique(course_id,name));
create table if not exists public.course_members(course_id bigint not null references public.courses(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,semester_id bigint references public.semesters(id) on delete set null,role text not null default 'student' check(role in('student','coordinator')),joined_at timestamptz not null default now(),primary key(course_id,user_id));
create table if not exists public.lesson_progress(user_id uuid not null references auth.users(id) on delete cascade,lesson_id text not null,completed boolean not null default false,score numeric,attempts int not null default 0,updated_at timestamptz not null default now(),primary key(user_id,lesson_id));
create table if not exists public.project_workspaces(user_id uuid primary key references auth.users(id) on delete cascade,current_stage int not null default 1,draft jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.feedback_responses(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete set null,context_type text not null,context_id text,responses jsonb not null,created_at timestamptz not null default now());
create table if not exists public.conversation_turns(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,mode text not null,user_text text not null,ai_reply text not null,feedback jsonb,created_at timestamptz not null default now());
insert into public.courses(slug,name,description) values('population-genetics','Population Genetics Coach','Theory, Models, Genomic Inference, and Scientific Reasoning') on conflict(slug) do nothing;

create or replace function public.assign_new_user_to_population_genetics() returns trigger language plpgsql security definer set search_path=public as $$
declare c_id bigint; s_id bigint; is_uni boolean; domain text;
begin
 domain:=lower(split_part(new.email,'@',2));
 is_uni:=domain in ('uni-koeln.de','smail.uni-koeln.de','hhu.de','uni-duesseldorf.de');
 insert into public.profiles(user_id,display_name,institutional_user) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)),is_uni) on conflict(user_id) do nothing;
 select id into c_id from public.courses where slug='population-genetics';
 if is_uni then select id into s_id from public.semesters where course_id=c_id and status='active' order by start_date desc nulls last limit 1; else s_id:=null; end if;
 insert into public.course_members(course_id,user_id,semester_id,role) values(c_id,new.id,s_id,'student') on conflict(course_id,user_id) do update set semester_id=excluded.semester_id;
 return new;
end $$;
drop trigger if exists on_auth_user_created_population_genetics on auth.users;
create trigger on_auth_user_created_population_genetics after insert on auth.users for each row execute function public.assign_new_user_to_population_genetics();

alter table public.profiles enable row level security; alter table public.course_members enable row level security; alter table public.lesson_progress enable row level security; alter table public.project_workspaces enable row level security; alter table public.feedback_responses enable row level security; alter table public.conversation_turns enable row level security;
create policy "own profile" on public.profiles for select using(auth.uid()=user_id);
create policy "own progress" on public.lesson_progress for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own project" on public.project_workspaces for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own conversation" on public.conversation_turns for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "submit feedback" on public.feedback_responses for insert with check(auth.uid()=user_id or user_id is null);
create policy "own membership" on public.course_members for select using(auth.uid()=user_id);
