-- Remote baseline migration.
--
-- The initial Population Genetics Coach schema represented by migration
-- version 20260718 has already been applied to the linked Supabase project.
--
-- The original SQL is retained in:
-- supabase/migration_archive/20260718_population_genetics_coach_v01.sql
--
-- This no-op file exists only to align the local migration history with
-- the existing remote migration record.
