import {useEffect,useState} from "react";
export type VoicePreferences={enabled:boolean;autoRead:boolean;rate:"slow"|"normal"};
const KEY="pg-voice-preferences"; const defaults:VoicePreferences={enabled:true,autoRead:false,rate:"normal"};
export function loadVoicePreferences(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return defaults}}
export function useVoicePreferences(){const [prefs,setPrefs]=useState(loadVoicePreferences);useEffect(()=>{const f=()=>setPrefs(loadVoicePreferences());window.addEventListener("pg-voice-change",f);return()=>window.removeEventListener("pg-voice-change",f)},[]);const update=(patch:Partial<VoicePreferences>)=>{const next={...prefs,...patch};localStorage.setItem(KEY,JSON.stringify(next));setPrefs(next);window.dispatchEvent(new Event("pg-voice-change"))};return{prefs,update}}
type DictationOptions={onInterim:(s:string)=>void;onFinal:(s:string)=>void;onError:(s:string)=>void;onEnd:()=>void}; let recognition:any=null;
export function startDictation(o:DictationOptions){const w=window as any;const C=w.SpeechRecognition||w.webkitSpeechRecognition;if(!C)return false;if(recognition)try{recognition.stop()}catch{};const r=new C();recognition=r;r.lang="en-GB";r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onresult=(e:any)=>{let interim="",final="";for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||"";e.results[i].isFinal?final+=t:interim+=t}o.onInterim(interim.trim());if(final.trim())o.onFinal(final.trim())};r.onerror=(e:any)=>o.onError(e.error||"speech recognition error");r.onend=()=>{recognition=null;o.onEnd()};const stop=()=>{try{r.stop()}catch{}};window.addEventListener("pg-stop-dictation",stop,{once:true});r.start();return true}
let current:SpeechSynthesisUtterance|null=null;let status={speaking:false,id:null as string|null};const listeners=new Set<()=>void>();const publish=(x:typeof status)=>{status=x;listeners.forEach(f=>f())};export const getSpeechStatus=()=>status;export const subscribeSpeechStatus=(f:()=>void)=>{listeners.add(f);return()=>listeners.delete(f)};
export function stopSpeaking(){speechSynthesis.cancel();current=null;publish({speaking:false,id:null})}
export function speakText(text:string,prefs:VoicePreferences,id:string){if(!prefs.enabled||!text.trim())return;stopSpeaking();const u=new SpeechSynthesisUtterance(text);current=u;u.lang="en-GB";u.rate=prefs.rate==="slow"?.78:.96;const voices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith("en"));u.voice=voices.find(v=>v.localService&&v.lang.toLowerCase().startsWith("en-gb"))||voices.find(v=>v.default)||voices[0]||null;u.onstart=()=>publish({speaking:true,id});u.onend=()=>{current=null;publish({speaking:false,id:null})};u.onerror=()=>{current=null;publish({speaking:false,id:null})};speechSynthesis.speak(u)}
