export type StageGuide = {
  purpose: string;
  prompts: string[];
  placeholder: string;
  checks: string[];
  aiFocus: string;
};

const g = (
  purpose: string,
  prompts: string[],
  placeholder: string,
  checks: string[],
  aiFocus: string,
): StageGuide => ({ purpose, prompts, placeholder, checks, aiFocus });

export const workspaceGuides: Record<string, StageGuide[]> = {
  project: [
    g(
      "Select a theme that is biologically meaningful, feasible with the available data, and clearly connected to population-genetic variation.",
      [
        "Name the biological phenomenon or contrast that interests you.",
        "Explain why variation among populations, environments, or time points is relevant to this theme.",
        "List the data types and populations currently available for investigating it.",
        "Narrow the theme until it can be addressed within one semester.",
      ],
      "Write a 150–250 word theme statement: biological context, focal variation, available data, and why the topic is feasible.",
      [
        "The theme is biological rather than merely a software exercise.",
        "The proposed scope fits the available samples and time.",
        "The theme can lead to a testable population-genetic question.",
        "I identified one likely limitation or missing resource.",
      ],
      "Evaluate biological relevance, feasibility, scope, and whether the theme can become a testable population-genetic project.",
    ),
    g(
      "Turn the broad theme into one focused question that specifies the biological response, comparison, and population context.",
      [
        "State the focal response or genetic pattern you want to explain.",
        "Name the populations, regions, environments, or time points being compared.",
        "Identify the evolutionary process or ecological contrast motivating the question.",
        "Remove methods from the question unless the project is explicitly methodological.",
      ],
      "Write one overarching question and one sentence explaining why answering it matters biologically.",
      [
        "The question is answerable with the available data.",
        "The question names a clear comparison or explanatory relationship.",
        "The question is not a list of methods.",
        "The biological relevance is explicit.",
      ],
      "Assess clarity, biological relevance, testability, scope, and alignment with the available course data.",
    ),
    g(
      "Translate the overarching question into directional or non-directional hypotheses and observable predictions.",
      [
        "Write the null hypothesis in biological terms.",
        "Write one or two alternative hypotheses.",
        "For each hypothesis, specify the expected pattern in the planned statistic or figure.",
        "Explain the biological reasoning connecting process to prediction.",
      ],
      "List each hypothesis followed by its biological rationale and one measurable prediction.",
      [
        "Each hypothesis is biologically justified.",
        "Each prediction is measurable in the available data.",
        "Predictions distinguish competing explanations where possible.",
        "I did not claim that one statistic alone proves a process.",
      ],
      "Check whether hypotheses are biologically reasoned, predictions are measurable, and alternative explanations remain distinguishable.",
    ),
    g(
      "Determine whether the available samples, metadata, genomic files, and computing resources can answer the proposed question.",
      [
        "List sample numbers by population, region, treatment, or time point.",
        "Check whether metadata and sample identifiers agree across files.",
        "Identify missing groups, unequal sample sizes, or confounded comparisons.",
        "State which analyses are feasible now and which would require additional data.",
      ],
      "Summarize data availability, sample balance, metadata quality, file readiness, and the main feasibility decision.",
      [
        "I verified sample identities and group sizes.",
        "I identified imbalances or confounding factors.",
        "I distinguished essential from optional analyses.",
        "My feasibility decision is explicit.",
      ],
      "Audit sample logic, metadata consistency, file readiness, confounding, and whether the proposed question is genuinely answerable.",
    ),
    g(
      "Define biologically meaningful groups and comparisons while avoiding pseudoreplication or confounding.",
      [
        "State the sampling unit and the population or group definition.",
        "Specify all primary and secondary comparisons.",
        "Explain how unequal sample size, relatedness, or missingness will be handled.",
        "Identify any comparison that cannot separate population, environment, and time effects.",
      ],
      "Describe the sampling design, comparison table, replication, exclusions, and one unavoidable limitation.",
      [
        "Groups correspond to the biological question.",
        "Replicates are independent at the relevant level.",
        "Unequal sample size and missing data are addressed.",
        "Confounded comparisons are acknowledged.",
      ],
      "Evaluate biological grouping, replication, comparison logic, sample balance, and confounding.",
    ),
    g(
      "Match each prediction to an approved analysis, expected output, and interpretation rule.",
      [
        "Create a table with prediction, input, analysis, output, and decision criterion.",
        "Explain why each statistic or plot addresses the corresponding prediction.",
        "State assumptions and required filtering for each analysis.",
        "Remove analyses that do not contribute to the biological question.",
      ],
      "Draft the prediction-to-analysis table and justify each analysis in one or two sentences.",
      [
        "Every analysis addresses a stated prediction.",
        "Inputs and outputs are clearly specified.",
        "Assumptions and filtering requirements are recorded.",
        "Redundant or decorative analyses were removed.",
      ],
      "Check alignment among hypotheses, predictions, analyses, outputs, assumptions, and interpretation criteria.",
    ),
    g(
      "Run the approved workflow reproducibly and preserve enough information for another student to repeat it.",
      [
        "Record software, version, command, parameters, input, and output for each step.",
        "Keep raw data separate from derived results.",
        "Save logs and note warnings, failed runs, and corrective actions.",
        "Use consistent names for populations, time points, and files.",
      ],
      "Provide a concise run log for the current analysis step, including command, input, output, version, and any problem encountered.",
      [
        "The workflow can be repeated from the record.",
        "Parameters and versions are included.",
        "Warnings and failed attempts are not hidden.",
        "File and population names remain consistent.",
      ],
      "Evaluate reproducibility, completeness of the run record, naming consistency, and whether problems were documented honestly.",
    ),
    g(
      "Convert numerical and graphical results into cautious biological conclusions while considering alternatives.",
      [
        "Describe the result before explaining it.",
        "State whether the result supports, contradicts, or does not resolve each prediction.",
        "Compare at least two plausible biological or technical explanations.",
        "Identify which additional evidence would distinguish those explanations.",
      ],
      "Write one result paragraph and one interpretation paragraph for a focal finding, including alternatives and limitations.",
      [
        "Observation and interpretation are separated.",
        "The conclusion matches the strength of evidence.",
        "At least one alternative explanation is considered.",
        "Unsupported causal language is avoided.",
      ],
      "Assess separation of result and interpretation, support for predictions, alternatives, causal overreach, and limitations.",
    ),
    g(
      "Design figures that directly answer the research question and legends that make them interpretable without the main text.",
      [
        "Choose the simplest figure type that communicates the result.",
        "Use informative axis labels, units, group names, and sample sizes.",
        "State the analysis, uncertainty, and statistical comparison in the legend.",
        "Check that colours, symbols, and panel labels are consistent and accessible.",
      ],
      "Draft the figure purpose, axis labels, legend, sample sizes, and one-sentence biological takeaway.",
      [
        "The figure answers a specific question.",
        "Axes, units, groups, and sample sizes are clear.",
        "The legend explains analysis and uncertainty.",
        "The takeaway does not overstate the result.",
      ],
      "Review question–figure alignment, labels, legend completeness, statistical reporting, and biological takeaway.",
    ),
    g(
      "Assemble a report in which each section contributes to one coherent scientific argument.",
      [
        "Check that the introduction ends with the overarching question and hypotheses.",
        "Ensure methods allow reproduction without becoming a command log.",
        "Present results in the same logical order as the questions and predictions.",
        "Use the discussion to interpret, compare alternatives, state limitations, and return to biological relevance.",
      ],
      "Paste one report section or provide a structured outline showing the argument from question to conclusion.",
      [
        "The scientific narrative is coherent across sections.",
        "Methods are reproducible and appropriately concise.",
        "Results follow the question order.",
        "Discussion distinguishes evidence, interpretation, and limitation.",
      ],
      "Evaluate scientific narrative, section function, reproducibility, result order, and discussion quality.",
    ),
    g(
      "Transform the report into a concise oral narrative with inference-led slides and balanced participation.",
      [
        "State the one-sentence story of the presentation.",
        "Give each slide an inference-led title rather than a topic label.",
        "Allocate time to introduction, main results, discussion, and questions.",
        "Rehearse transitions and prepare answers to likely biological and methodological questions.",
      ],
      "Provide the presentation story, slide sequence, timing, and three likely questions with concise answers.",
      [
        "The talk has one clear narrative spine.",
        "Slide titles state the inference or purpose.",
        "Timing leaves space for discussion and questions.",
        "All members can explain the complete project.",
      ],
      "Assess narrative coherence, slide logic, timing, transitions, and readiness for questions.",
    ),
    g(
      "Complete a final scientific and technical audit, then reflect on what was learned and what should change next time.",
      [
        "Check every claim against the corresponding result.",
        "Verify figures, legends, references, filenames, and required submission components.",
        "Use the rubric to identify the strongest and weakest project elements.",
        "Name one conceptual, analytical, and communication skill gained.",
      ],
      "Write the final submission checklist, rubric self-score, unresolved concern, and three concrete lessons for future work.",
      [
        "All required files and sections are present.",
        "Claims match the evidence.",
        "The self-assessment is specific rather than generic.",
        "Next steps are concrete and realistic.",
      ],
      "Perform a final audit of completeness, evidence–claim alignment, rubric-based self-assessment, and reflective next steps.",
    ),
  ],
  practical: [
    g(
      "Establish a reproducible project structure before analysis begins.",
      [
        "Identify the biological question for the session.",
        "Create folders for raw data, scripts, results, figures, and logs.",
        "Inspect filenames and metadata without altering raw files.",
        "Record the expected input and output of the session.",
      ],
      "Describe your project structure and list the exact files you will treat as immutable raw inputs.",
      [
        "Raw data are protected.",
        "Folders have clear purposes.",
        "Inputs and outputs are identified.",
        "The session goal is biologically explicit.",
      ],
      "Check project organization, raw-data protection, and whether the practical goal and outputs are clear.",
    ),
    g(
      "Use R objects and plots to inspect biological data accurately.",
      [
        "Import the supplied table and verify dimensions and column types.",
        "Summarize missing values and group sizes.",
        "Create the required plot with meaningful labels.",
        "Explain what the plot shows and what it cannot show.",
      ],
      "Paste the key R commands or describe the resulting object and plot, followed by a biological interpretation.",
      [
        "Dimensions and types were checked.",
        "Missingness and group sizes were inspected.",
        "Plot labels and units are correct.",
        "Interpretation does not exceed the plot.",
      ],
      "Evaluate data inspection, plotting choices, labels, and biological interpretation.",
    ),
    g(
      "Use shell and HPC commands safely and reproducibly.",
      [
        "Confirm the working directory and list files before running commands.",
        "Distinguish login-node tasks from compute-node tasks.",
        "Specify resources, environment, and output logs in the job script.",
        "Check exit status and output files after completion.",
      ],
      "Provide the command sequence or job-script block and explain the purpose of each step.",
      [
        "The working directory is verified.",
        "Compute-intensive work is submitted appropriately.",
        "Resources and logs are specified.",
        "Outputs and errors are checked.",
      ],
      "Check command safety, HPC resource logic, logging, and post-run validation.",
    ),
    g(
      "Assess read quality and mapping before variant analysis.",
      [
        "Inspect read-quality summaries and adapter or low-quality signals.",
        "Record the reference genome and mapping command.",
        "Check mapping rate, coverage, and duplicated or problematic reads.",
        "Decide whether the data are suitable for downstream analysis.",
      ],
      "Summarize the QC and mapping evidence and state a proceed/revise decision.",
      [
        "QC metrics are reported.",
        "Reference and mapping settings are recorded.",
        "Mapping quality is interpreted cautiously.",
        "The decision is evidence-based.",
      ],
      "Evaluate QC completeness, mapping evidence, and the downstream suitability decision.",
    ),
    g(
      "Create and justify a transparent VCF filtering strategy.",
      [
        "Inspect variant and genotype-level quality fields.",
        "Apply the supplied filtering sequence in the correct order.",
        "Record variants and samples retained after each step.",
        "Explain how each filter affects bias and usable information.",
      ],
      "Provide the filtering table: criterion, rationale, count before, count after, and potential consequence.",
      [
        "Filter order is recorded.",
        "Thresholds match the practical instructions.",
        "Variant loss is quantified.",
        "Potential bias from filtering is discussed.",
      ],
      "Check threshold use, filtering order, count tracking, and biological consequences.",
    ),
    g(
      "Estimate structure and diversity using the approved practical workflow.",
      [
        "Confirm population labels and sample numbers.",
        "Run the required structure and diversity analyses.",
        "Inspect whether results are robust to sample imbalance or relatedness.",
        "Link each output to a biological question.",
      ],
      "Summarize the main outputs and provide one cautious biological interpretation for each.",
      [
        "Sample groups are verified.",
        "Outputs are linked to questions.",
        "Confounding and imbalance are considered.",
        "No single plot is treated as definitive proof.",
      ],
      "Evaluate sample grouping, analysis–question alignment, confounding, and interpretation.",
    ),
    g(
      "Integrate practical outputs into one reproducible biological conclusion.",
      [
        "Select the outputs that directly answer the session question.",
        "Check agreement or conflict among analyses.",
        "Identify technical and biological alternatives.",
        "Package scripts, logs, figures, and a concise readme.",
      ],
      "Write the integrated conclusion and list the exact files included in the reproducible result package.",
      [
        "Multiple outputs are integrated.",
        "Conflicting evidence is acknowledged.",
        "Alternatives and limitations are stated.",
        "The package can be rerun and understood.",
      ],
      "Assess integration, treatment of conflicting evidence, limitations, and reproducibility of the final package.",
    ),
  ],
  analysis: [
    g(
      "Verify that samples, metadata, and genomic files represent the intended biological groups.",
      [
        "Compare sample IDs across metadata and genomic files.",
        "Count samples per population or time point.",
        "Identify duplicates, relatives, missing metadata, or unexpected samples.",
        "State which samples will be included or excluded and why.",
      ],
      "Provide the sample-audit table and inclusion/exclusion decisions.",
      [
        "Identifiers agree across files.",
        "Group sizes are known.",
        "Exclusions are justified.",
        "Potential bias is recorded.",
      ],
      "Audit sample identity, group balance, exclusion logic, and bias.",
    ),
    g(
      "Evaluate whether filtering decisions produce a defensible analysis dataset.",
      [
        "List every filter and threshold in execution order.",
        "Quantify variants and samples removed at each step.",
        "Inspect missingness, depth, quality, and allele-frequency effects.",
        "Explain why the final dataset is appropriate for the planned analyses.",
      ],
      "Write the filtering audit with counts, rationale, and potential consequences.",
      [
        "All filters are traceable.",
        "Counts before and after are recorded.",
        "Threshold consequences are considered.",
        "The final dataset matches analysis assumptions.",
      ],
      "Evaluate traceability, count tracking, threshold rationale, and downstream suitability.",
    ),
    g(
      "Use PCA and relatedness to inspect major covariance patterns and sample dependence.",
      [
        "Report variance explained by displayed axes.",
        "Identify clusters, gradients, and outlying samples without assigning causes prematurely.",
        "Compare PCA patterns with geography, metadata, and relatedness.",
        "Decide whether relatives or outliers require sensitivity analysis.",
      ],
      "Describe the PCA and relatedness patterns, then list at least two plausible explanations.",
      [
        "Axes and variance explained are reported.",
        "Pattern description precedes interpretation.",
        "Relatedness is considered.",
        "Alternative explanations are stated.",
      ],
      "Assess PCA reporting, relatedness, alternative explanations, and overinterpretation.",
    ),
    g(
      "Interpret ancestry estimates as model-dependent summaries rather than literal population histories.",
      [
        "State the tested range of K and the model-selection evidence.",
        "Compare repeated runs and label consistency.",
        "Relate ancestry patterns to PCA and sampling geography.",
        "Identify effects of uneven sampling, LD, and model assumptions.",
      ],
      "Summarize the supported ancestry patterns and the main reasons for caution.",
      [
        "K selection is justified.",
        "Run consistency is checked.",
        "Results are compared with PCA and geography.",
        "Model limitations are explicit.",
      ],
      "Evaluate K selection, run stability, cross-method comparison, and model limitations.",
    ),
    g(
      "Use FST to quantify differentiation while retaining its dependence on within-population variation and sampling.",
      [
        "State the estimator and genomic unit used.",
        "Report genome-wide and locus/window-level patterns.",
        "Compare differentiation among the relevant population pairs.",
        "Avoid interpreting high FST as selection without additional evidence.",
      ],
      "Describe the differentiation pattern and provide demographic, sampling, and selective alternatives.",
      [
        "Estimator and unit are named.",
        "Pairwise comparisons are clear.",
        "Within-population variation is considered.",
        "High values are not equated automatically with selection.",
      ],
      "Assess estimator reporting, pairwise logic, genomic scale, and causal restraint.",
    ),
    g(
      "Interpret π, θ, and Tajima’s D jointly to describe diversity and allele-frequency patterns.",
      [
        "Report how each statistic was calculated and summarized.",
        "Compare populations using the same genomic windows or sites.",
        "Explain how π and θ contribute to the sign of Tajima’s D.",
        "Consider demographic history, selection, structure, and technical bias.",
      ],
      "Write a joint interpretation of π, θ, and Tajima’s D for the focal comparison.",
      [
        "Statistics are defined consistently.",
        "Comparisons use equivalent genomic units.",
        "The sign of D is explained mechanistically.",
        "Multiple processes are considered.",
      ],
      "Evaluate joint statistical interpretation, comparability, mechanism, and alternatives.",
    ),
    g(
      "Use the site-frequency spectrum to compare demographic expectations with observed allele-frequency data.",
      [
        "State whether the SFS is folded or unfolded and why.",
        "Describe singletons, rare, intermediate, and high-frequency classes.",
        "Specify the demographic models being compared.",
        "Evaluate model fit and residual discrepancies.",
      ],
      "Summarize the observed SFS, candidate models, fit evidence, and unresolved mismatch.",
      [
        "Polarisation status is clear.",
        "Frequency classes are described.",
        "Models are biologically motivated.",
        "Residuals and uncertainty are reported.",
      ],
      "Assess SFS construction, model motivation, fit evidence, and residual interpretation.",
    ),
    g(
      "Use LD patterns to define genomic dependence and appropriate mapping or window scales.",
      [
        "Describe LD decay by population or time point.",
        "State how sample size, structure, and marker density may affect the estimate.",
        "Use the observed scale to justify gene-mapping or window choices.",
        "Avoid treating an LD block as a single causal variant.",
      ],
      "Report LD decay or block patterns and justify the chosen downstream genomic scale.",
      [
        "LD is compared on equivalent terms.",
        "Potential confounders are discussed.",
        "Window or mapping scale is justified.",
        "Causality is not assigned to whole blocks.",
      ],
      "Evaluate LD comparison, confounding, scale choice, and causal restraint.",
    ),
    g(
      "Distinguish exceptional temporal or genomic change from neutral expectation without equating outliers with adaptation.",
      [
        "State how the neutral envelope or outlier threshold was produced.",
        "Report positive and negative changes separately when biologically relevant.",
        "Check sensitivity to sample size, starting frequency, and linkage.",
        "Identify evidence needed to support selection beyond outlier status.",
      ],
      "Summarize the scan, threshold logic, outlier counts, and at least two alternative explanations.",
      [
        "Threshold construction is transparent.",
        "Direction and starting frequency are considered.",
        "Linkage and sample size are addressed.",
        "Outliers are treated as candidates, not proof.",
      ],
      "Assess threshold logic, directionality, confounding, and claims about selection.",
    ),
    g(
      "Connect candidate regions to genes and functions without overstating annotation or enrichment.",
      [
        "Define the mapping window or LD-based region.",
        "Record how variants were assigned to genes.",
        "State the tested gene universe and enrichment method.",
        "Interpret enriched terms as hypotheses rather than validated mechanisms.",
      ],
      "Provide the mapping rule, gene universe, top functional result, and one cautious biological interpretation.",
      [
        "Mapping scale is justified.",
        "The background gene universe is correct.",
        "Multiple testing is considered.",
        "Functional results remain hypothesis-generating.",
      ],
      "Evaluate gene mapping, enrichment background, multiple testing, and biological restraint.",
    ),
    g(
      "Integrate structure, diversity, demography, LD, and outlier evidence into one ranked interpretation.",
      [
        "List the strongest observations independent of interpretation.",
        "Identify which processes are supported by multiple analyses.",
        "Explain contradictions among analyses.",
        "Rank conclusions as strong, moderate, tentative, or unresolved.",
      ],
      "Write a synthesis with evidence table, competing explanations, and confidence ranking.",
      [
        "Evidence is separated from inference.",
        "Convergent and conflicting analyses are identified.",
        "Confidence matches evidence strength.",
        "Unresolved questions remain visible.",
      ],
      "Assess integration, contradiction handling, confidence calibration, and competing explanations.",
    ),
    g(
      "Package data provenance, scripts, parameters, results, and interpretation for complete reproducibility.",
      [
        "Create a readme describing order of execution.",
        "Record software versions and environments.",
        "Link every final figure or table to its generating script and input.",
        "Remove temporary files but preserve logs and key intermediate summaries.",
      ],
      "Draft the readme structure and reproducibility checklist.",
      [
        "Execution order is clear.",
        "Versions and parameters are recorded.",
        "Outputs trace back to scripts and inputs.",
        "Logs and essential intermediates are preserved.",
      ],
      "Evaluate whether another analyst could reproduce and understand the complete result package.",
    ),
  ],
  writing: [
    g(
      "Choose a title that states the biological system, focal relationship, and scale without claiming more than the study tested.",
      [
        "Identify the biological subject and main comparison.",
        "Remove vague phrases and unnecessary methods.",
        "Check that causal words are justified.",
        "Keep the title concise and informative.",
      ],
      "Draft three title options and explain which is strongest.",
      [
        "The biological system is named.",
        "The main comparison is visible.",
        "Causal language is justified.",
        "The title is concise.",
      ],
      "Evaluate precision, scope, biological informativeness, and causal wording.",
    ),
    g(
      "Build an introduction that moves from broad biological relevance to the specific knowledge gap.",
      [
        "Open with the ecological or evolutionary problem.",
        "Introduce only concepts needed for the project.",
        "Summarize what is known and identify the unresolved gap.",
        "End the section by narrowing toward the study system.",
      ],
      "Draft the paragraph sequence and the purpose of each paragraph.",
      [
        "The introduction narrows logically.",
        "The knowledge gap is explicit.",
        "Background is relevant rather than encyclopedic.",
        "The study system enters at the right point.",
      ],
      "Assess narrative narrowing, relevance, gap definition, and paragraph function.",
    ),
    g(
      "State the overarching question, hypotheses, and predictions as the logical endpoint of the introduction.",
      [
        "Write the overarching biological question.",
        "State each hypothesis with biological rationale.",
        "Give a measurable prediction for each hypothesis.",
        "Ensure terminology matches later methods and results.",
      ],
      "Paste the final question, hypotheses, rationales, and predictions.",
      [
        "Question and hypotheses are distinct.",
        "Predictions are measurable.",
        "Rationales are biological.",
        "Terminology is consistent.",
      ],
      "Evaluate clarity, testability, rationale, prediction quality, and terminology.",
    ),
    g(
      "Write a reproducible study-design and sampling section.",
      [
        "Describe populations, locations, time points, and sample numbers.",
        "Explain selection, exclusion, and grouping of samples.",
        "Identify replication and potential imbalance.",
        "State permits or ethical considerations where relevant.",
      ],
      "Draft the sampling and study-design paragraph with sample numbers.",
      [
        "Sampling units are clear.",
        "Group definitions and sizes are reported.",
        "Exclusions are justified.",
        "Limitations are acknowledged.",
      ],
      "Assess reproducibility, sample reporting, grouping, and limitations.",
    ),
    g(
      "Describe bioinformatic and statistical methods with enough detail to reproduce the analysis.",
      [
        "Organize methods in execution order.",
        "Report software, versions, parameters, and reference resources.",
        "Explain filtering and statistical decisions.",
        "Avoid replacing methods with raw command dumps.",
      ],
      "Draft one methods subsection for a focal analysis.",
      [
        "Execution order is clear.",
        "Versions and parameters are included.",
        "Decisions are justified.",
        "The text is reproducible but readable.",
      ],
      "Evaluate method completeness, order, parameter reporting, rationale, and readability.",
    ),
    g(
      "Open the results with data-quality and sample-retention information needed to trust later analyses.",
      [
        "Report initial and retained samples and variants.",
        "Summarize missingness, depth, mapping, or filtering outcomes.",
        "Identify exclusions and their reasons.",
        "Do not interpret biological processes in this subsection.",
      ],
      "Draft the QC results paragraph and identify the supporting table or figure.",
      [
        "Counts are exact.",
        "Exclusions are transparent.",
        "QC evidence is linked to outputs.",
        "Interpretation is reserved for later.",
      ],
      "Assess completeness, transparency, linkage to evidence, and separation from discussion.",
    ),
    g(
      "Present population-structure and diversity results in the order required to answer the question.",
      [
        "Describe patterns before explaining them.",
        "Report key values, uncertainty, and sample sizes.",
        "Refer precisely to figures and tables.",
        "Avoid repeating all visual details in prose.",
      ],
      "Draft one structure or diversity result paragraph.",
      [
        "The main pattern appears first.",
        "Key statistics and uncertainty are reported.",
        "Figure references are precise.",
        "No unsupported explanation is added.",
      ],
      "Evaluate result-first writing, quantitative reporting, figure linkage, and interpretation leakage.",
    ),
    g(
      "Present focal hypothesis tests or genomic results as direct answers to predictions.",
      [
        "Begin with the tested prediction.",
        "Report direction, effect, uncertainty, and statistical evidence.",
        "State whether the result supports the prediction without explaining why.",
        "Include negative or non-significant results.",
      ],
      "Draft the focal result paragraph for one hypothesis.",
      [
        "The prediction is identifiable.",
        "Effect direction and evidence are reported.",
        "Support is stated cautiously.",
        "Negative results are retained.",
      ],
      "Assess prediction alignment, quantitative reporting, restraint, and completeness.",
    ),
    g(
      "Interpret results through competing explanations and explicit limitations.",
      [
        "Return to each hypothesis.",
        "Compare findings with demographic, selective, structural, and technical alternatives.",
        "Identify limitations that affect interpretation rather than listing generic weaknesses.",
        "State what additional evidence would resolve uncertainty.",
      ],
      "Draft one discussion subsection around a major result.",
      [
        "The result is not simply repeated.",
        "Alternatives are compared.",
        "Limitations affect the specific inference.",
        "Future evidence is concrete.",
      ],
      "Evaluate depth of interpretation, alternatives, meaningful limitations, and future tests.",
    ),
    g(
      "Write an abstract that accurately compresses the complete study.",
      [
        "Give one sentence of context and the main question.",
        "Summarize data and core methods briefly.",
        "Report the principal results with direction.",
        "End with a restrained biological conclusion.",
      ],
      "Draft a structured abstract within the required word limit.",
      [
        "All four functions are present.",
        "Results are specific.",
        "No new information appears.",
        "The conclusion matches evidence.",
      ],
      "Assess completeness, specificity, compression, and evidence–claim alignment.",
    ),
    g(
      "Use references and terminology consistently and transparently.",
      [
        "Check that every citation appears in the reference list and vice versa.",
        "Use one naming convention for populations, statistics, genes, and software.",
        "Define abbreviations on first use.",
        "Verify that borrowed claims are cited appropriately.",
      ],
      "List the main consistency checks and any corrections required.",
      [
        "Citations and references match.",
        "Terminology is consistent.",
        "Abbreviations are defined.",
        "Software and data resources are cited appropriately.",
      ],
      "Audit reference consistency, terminology, abbreviations, and attribution.",
    ),
    g(
      "Complete a final rubric-based edit focused on scientific logic rather than surface grammar alone.",
      [
        "Trace the question through hypotheses, methods, results, and discussion.",
        "Check every figure, table, caption, and cross-reference.",
        "Remove overclaiming, repetition, and unsupported statements.",
        "Read the report once for scientific argument and once for language.",
      ],
      "Provide the final revision plan ordered by scientific importance.",
      [
        "The question–evidence chain is intact.",
        "Figures and references are correct.",
        "Overclaims and repetition are removed.",
        "The revision plan prioritizes major issues.",
      ],
      "Evaluate coherence, evidence–claim alignment, technical completeness, and revision priorities.",
    ),
  ],
  presentation: [
    g(
      "Define the one-sentence scientific story that the audience should remember.",
      [
        "State the biological problem.",
        "Name the focal question and comparison.",
        "State the central result or unresolved outcome.",
        "Explain why it matters.",
      ],
      "Write the one-sentence story and a 20-second opening.",
      [
        "The story is biological.",
        "The question is clear.",
        "The outcome is accurate.",
        "Relevance is explicit.",
      ],
      "Evaluate focus, biological relevance, accuracy, and memorability.",
    ),
    g(
      "Build a logical slide sequence around questions and inferences.",
      [
        "Arrange slides as context → gap → question → evidence → interpretation → conclusion.",
        "Remove slides that do not advance the story.",
        "Use one main message per slide.",
        "Check that each transition motivates the next slide.",
      ],
      "List slide titles in sequence and state the transition between each major section.",
      [
        "The sequence follows scientific logic.",
        "Every slide has one purpose.",
        "Transitions are explicit.",
        "Redundant content is removed.",
      ],
      "Assess narrative order, slide purpose, transitions, and redundancy.",
    ),
    g(
      "Create an introduction that is biologically motivated but proportionate to the talk.",
      [
        "Use only background needed to understand the question.",
        "Show the study system and comparison clearly.",
        "State the gap before the question.",
        "Reach the objectives early enough to preserve time for results.",
      ],
      "Draft the introduction slide sequence and approximate timing.",
      [
        "Background is relevant.",
        "The gap is explicit.",
        "Objectives appear early.",
        "Timing leaves room for results.",
      ],
      "Evaluate relevance, gap clarity, timing, and transition to the question.",
    ),
    g(
      "Present methods as a transparent analytical design rather than a software inventory.",
      [
        "Show sampling and comparison structure.",
        "Summarize the pipeline at the level needed to understand evidence.",
        "Highlight assumptions or choices that affect interpretation.",
        "Move implementation details to backup slides.",
      ],
      "Describe the methods figure and the two choices the audience must understand.",
      [
        "Sampling and comparisons are clear.",
        "Pipeline detail is proportionate.",
        "Critical assumptions are visible.",
        "Backup details are separated.",
      ],
      "Assess method clarity, proportionality, assumptions, and use of backup slides.",
    ),
    g(
      "Design result figures that can be understood quickly during oral delivery.",
      [
        "Simplify axes, labels, legends, and annotations.",
        "Highlight the focal comparison without hiding uncertainty.",
        "Use consistent visual encoding across slides.",
        "Write an inference-led title for each figure.",
      ],
      "Provide one figure title, take-home message, and 30-second explanation.",
      [
        "The title states the inference.",
        "The focal comparison is visible.",
        "Uncertainty remains visible.",
        "The explanation matches the figure.",
      ],
      "Evaluate figure readability, title quality, uncertainty, and spoken explanation.",
    ),
    g(
      "Link each main result directly to the corresponding question or prediction.",
      [
        "Introduce the question before displaying the figure.",
        "Describe the visual pattern before interpretation.",
        "State the result in one sentence.",
        "Use the transition to motivate the next analysis.",
      ],
      "Draft the spoken script for one result slide and its transition.",
      [
        "Question and result are linked.",
        "Description precedes explanation.",
        "The takeaway is concise.",
        "The transition is logical.",
      ],
      "Assess question–result linkage, sequencing, concision, and transition.",
    ),
    g(
      "Use the discussion to weigh biological explanations and limitations.",
      [
        "Return to the main hypotheses.",
        "Compare at least two explanations.",
        "Identify the limitation that most affects the conclusion.",
        "State what evidence would strengthen the inference.",
      ],
      "Draft a 45-second discussion segment for the main result.",
      [
        "Hypotheses are revisited.",
        "Alternatives are compared.",
        "The key limitation is specific.",
        "Next evidence is concrete.",
      ],
      "Evaluate interpretation, alternatives, limitation specificity, and next evidence.",
    ),
    g(
      "End with a concise conclusion that answers the question rather than listing analyses.",
      [
        "State the strongest supported conclusion.",
        "Identify what remains unresolved.",
        "Return to the broader biological relevance.",
        "Avoid introducing new results.",
      ],
      "Write the final three take-home messages and closing sentence.",
      [
        "Conclusions answer the question.",
        "Uncertainty is retained.",
        "Biological relevance is restored.",
        "No new result is introduced.",
      ],
      "Assess question resolution, restraint, broader relevance, and closure.",
    ),
    g(
      "Allocate time so that results and interpretation dominate the presentation.",
      [
        "Assign time to every section.",
        "Rehearse at normal speaking speed.",
        "Mark slides that can be shortened or skipped.",
        "Reserve time for questions.",
      ],
      "Provide the timing plan and the first cuts you would make if over time.",
      [
        "Timing was tested aloud.",
        "Results receive the largest share.",
        "Cuts preserve the story.",
        "Question time is protected.",
      ],
      "Evaluate realism of timing, priorities, contingency cuts, and question allowance.",
    ),
    g(
      "Use transitions and shared speaking roles to make a group presentation feel coherent.",
      [
        "Assign sections based on narrative continuity.",
        "Write the handover sentence between speakers.",
        "Standardize terminology and visual style.",
        "Ensure every member can answer questions about the whole project.",
      ],
      "List speaker assignments and exact handover lines.",
      [
        "Assignments follow the story.",
        "Handovers are natural.",
        "Terminology is consistent.",
        "All speakers understand the full project.",
      ],
      "Assess group coherence, handovers, consistency, and shared understanding.",
    ),
    g(
      "Prepare for questions by anticipating conceptual, methodological, and interpretive challenges.",
      [
        "Write likely questions about biological relevance.",
        "Prepare questions about assumptions, sampling, and statistics.",
        "Identify one limitation you will state openly.",
        "Practice concise answers that distinguish evidence from speculation.",
      ],
      "Provide six likely questions and answers, including one you cannot fully resolve.",
      [
        "Questions cover biology, methods, and interpretation.",
        "Answers are concise.",
        "Limitations are acknowledged.",
        "Uncertainty is handled honestly.",
      ],
      "Evaluate coverage, concision, honesty, and scientific reasoning in answers.",
    ),
    g(
      "Run a final rehearsal and technical audit under realistic conditions.",
      [
        "Present from beginning to end without interruption.",
        "Check fonts, figures, videos, animations, and file compatibility.",
        "Record timing and unclear transitions.",
        "Make only high-priority final edits.",
      ],
      "Summarize rehearsal timing, technical risks, weak points, and final corrections.",
      [
        "The full talk was rehearsed.",
        "Technical compatibility was checked.",
        "Weak transitions were identified.",
        "Final edits are prioritized.",
      ],
      "Assess readiness, timing, technical risk, and final revision priorities.",
    ),
  ],
  exam: [
    g(
      "Diagnose current strengths and weaknesses before revision.",
      [
        "List topics you can explain without notes.",
        "Identify topics where you recognize terms but cannot interpret figures.",
        "Review previous self-check errors.",
        "Prioritize high-impact gaps.",
      ],
      "Write a ranked diagnostic of strong, developing, and weak topics.",
      [
        "The ranking is evidence-based.",
        "Interpretation skills are assessed.",
        "Past errors inform priorities.",
        "The plan is realistic.",
      ],
      "Evaluate diagnostic accuracy and revision prioritization.",
    ),
    g(
      "Review allele and genotype frequencies, HWE, and core assumptions.",
      [
        "Calculate frequencies from counts.",
        "Check HWE expectations.",
        "Explain deviations without assigning one cause automatically.",
        "Practice interpretation in biological context.",
      ],
      "Solve one representative problem and explain every step.",
      [
        "Counts and frequencies are distinguished.",
        "Calculations are correct.",
        "Assumptions are stated.",
        "Interpretation remains cautious.",
      ],
      "Evaluate calculation, assumptions, and interpretation.",
    ),
    g(
      "Review drift models, fixation, and effective population size.",
      [
        "Explain stochastic change in finite populations.",
        "Compare census size and effective size.",
        "Interpret fixation probability and time conceptually.",
        "Connect drift strength to population size.",
      ],
      "Write a concise explanation using one worked example.",
      [
        "Random change is explained correctly.",
        "Ne is distinguished from census size.",
        "Fixation is interpreted probabilistically.",
        "Population-size effects are clear.",
      ],
      "Evaluate conceptual accuracy and model interpretation.",
    ),
    g(
      "Review structure, migration, and differentiation.",
      [
        "Interpret FST and its limitations.",
        "Connect migration and drift to structure.",
        "Compare PCA, ancestry, and FST outputs.",
        "Recognize sampling and relatedness effects.",
      ],
      "Interpret a hypothetical structure figure and pairwise FST table.",
      [
        "Methods are not treated as equivalent.",
        "Sampling effects are considered.",
        "FST is not equated with selection.",
        "Evidence is integrated.",
      ],
      "Evaluate comparative interpretation of structure methods.",
    ),
    g(
      "Review diversity, coalescence, SFS, and Tajima’s D.",
      [
        "Define π, θ, and coalescent time.",
        "Explain the SFS classes.",
        "Relate Tajima’s D to differences among estimators.",
        "Compare demographic and selective explanations.",
      ],
      "Write a structured interpretation of a diversity and Tajima’s D result.",
      [
        "Statistics are defined.",
        "Frequency classes are understood.",
        "The sign of D is explained.",
        "Multiple processes are considered.",
      ],
      "Evaluate definitions, mechanisms, and alternatives.",
    ),
    g(
      "Review selection and temporal genomic change.",
      [
        "Distinguish directional, balancing, and purifying selection.",
        "Interpret allele-frequency change against drift expectations.",
        "Consider starting frequency and linkage.",
        "Treat outliers as candidates rather than proof.",
      ],
      "Explain one temporal outlier result with alternatives.",
      [
        "Selection modes are distinguished.",
        "Drift expectation is considered.",
        "Confounders are named.",
        "Claims are appropriately cautious.",
      ],
      "Evaluate selection reasoning and temporal interpretation.",
    ),
    g(
      "Review genomic workflows and quality control.",
      [
        "Order the steps from reads to analysis-ready variants.",
        "Explain the purpose of major QC and filtering steps.",
        "Identify common file and metadata errors.",
        "Connect technical quality to biological inference.",
      ],
      "Create a workflow diagram with decision points and failure modes.",
      [
        "Step order is correct.",
        "QC purposes are understood.",
        "Failure modes are recognized.",
        "Technical choices are linked to inference.",
      ],
      "Evaluate workflow understanding and quality-control reasoning.",
    ),
    g(
      "Practice figure interpretation across course topics.",
      [
        "Describe axes, groups, and patterns first.",
        "Identify the question addressed by the figure.",
        "State the supported conclusion.",
        "Name one alternative or limitation.",
      ],
      "Interpret one figure using the four-step structure.",
      [
        "Description precedes interpretation.",
        "The question is identified.",
        "Conclusion matches evidence.",
        "A limitation is included.",
      ],
      "Evaluate figure-reading structure and restraint.",
    ),
    g(
      "Practice numerical problems under exam conditions.",
      [
        "Write the formula before substitution.",
        "Define symbols and units.",
        "Show intermediate steps.",
        "Interpret the final value biologically.",
      ],
      "Solve a timed numerical problem and review errors.",
      [
        "Formula and symbols are correct.",
        "Steps are visible.",
        "Arithmetic is checked.",
        "Biological interpretation is included.",
      ],
      "Evaluate setup, calculation, and interpretation.",
    ),
    g(
      "Complete a mixed mock examination.",
      [
        "Use the official time limit.",
        "Answer without notes.",
        "Mark uncertain responses.",
        "Review each error by category: concept, calculation, reading, or wording.",
      ],
      "Record the score and classify every error.",
      [
        "Conditions were realistic.",
        "Uncertainty was marked.",
        "Errors were classified.",
        "Weak topics were updated.",
      ],
      "Evaluate mock-exam performance and error diagnosis.",
    ),
    g(
      "Build targeted revision from recurring errors.",
      [
        "Group errors by underlying misconception.",
        "Return to the relevant lesson and concept cards.",
        "Create one new example for each weak concept.",
        "Retest after a delay.",
      ],
      "Write the targeted revision plan and retest schedule.",
      [
        "Revision targets causes, not isolated answers.",
        "Relevant lessons are identified.",
        "New examples are created.",
        "Retesting is scheduled.",
      ],
      "Evaluate whether revision addresses recurring misconceptions.",
    ),
    g(
      "Complete a final readiness check focused on explanation and interpretation.",
      [
        "Explain each major topic aloud in two minutes.",
        "Solve one calculation from each quantitative block.",
        "Interpret one unfamiliar figure.",
        "Identify remaining uncertainty and an exam strategy.",
      ],
      "Write the final readiness summary and exam-day strategy.",
      [
        "Major topics can be explained.",
        "Core calculations can be completed.",
        "Unfamiliar figures can be approached systematically.",
        "Remaining gaps are acknowledged.",
      ],
      "Evaluate final readiness and strategy.",
    ),
  ],
  feedback: [
    g(
      "Record your starting confidence so later change can be interpreted.",
      [
        "Rate confidence in theory, calculations, R, shell/HPC, genomic analysis, writing, and presentation.",
        "Name one topic you expect to find difficult.",
        "State one skill you want to develop.",
        "Explain what useful support would look like.",
      ],
      "Write a baseline reflection with ratings and two concrete learning goals.",
      [
        "Ratings cover distinct skill areas.",
        "Goals are specific.",
        "Expected difficulty is named.",
        "Support needs are actionable.",
      ],
      "Evaluate specificity and usefulness of the baseline reflection.",
    ),
    g(
      "Give feedback on a specific lecture module, not the course in general.",
      [
        "Select the module and lesson.",
        "Identify the clearest concept and why it became clear.",
        "Identify one unresolved concept or equation.",
        "Suggest one concrete change to explanation, pacing, example, or figure.",
      ],
      "Name the module/lesson and provide one strength, one difficulty, and one actionable suggestion.",
      [
        "The module is identified.",
        "Feedback refers to specific content.",
        "The difficulty is explained.",
        "The suggestion is actionable.",
      ],
      "Evaluate specificity, relevance, and actionability of lecture feedback.",
    ),
    g(
      "Evaluate a specific practical session and its learning outcome.",
      [
        "Select the practical session.",
        "State which task you completed successfully.",
        "Describe the command, analysis, or interpretation step that caused difficulty.",
        "Suggest one resource or demonstration that would help.",
      ],
      "Name the practical and provide evidence of what worked, what failed, and what support is needed.",
      [
        "The practical is identified.",
        "Feedback refers to an actual task.",
        "The obstacle is diagnosed.",
        "Requested support is concrete.",
      ],
      "Evaluate specificity and diagnostic quality of practical feedback.",
    ),
    g(
      "Use assessment results to identify the reason for mistakes.",
      [
        "Select the lesson assessment or exam block.",
        "Classify errors as conceptual, numerical, interpretive, or reading-related.",
        "Explain one incorrect answer in your own words.",
        "State the revision action you will take.",
      ],
      "Summarize the assessment, error pattern, corrected reasoning, and revision action.",
      [
        "The assessment is identified.",
        "Errors are classified.",
        "Corrected reasoning is provided.",
        "The revision action is specific.",
      ],
      "Evaluate error diagnosis and the usefulness of the revision response.",
    ),
    g(
      "Reflect on the current research-project stage and request targeted help.",
      [
        "Identify the project stage and current deliverable.",
        "State what has been completed.",
        "Name the decision or obstacle preventing progress.",
        "Ask one focused question for instructor or AI feedback.",
      ],
      "Write the project-stage update, evidence of progress, obstacle, and focused question.",
      [
        "The stage is identified.",
        "Progress is evidenced.",
        "The obstacle is specific.",
        "The help request is focused.",
      ],
      "Evaluate project-status clarity and whether the requested support can be acted upon.",
    ),
    g(
      "Request feedback on a defined piece of scientific writing.",
      [
        "Name the section and its intended function.",
        "Paste or summarize the passage under review.",
        "State whether you need help with logic, evidence, structure, or language.",
        "Identify one concern you already notice.",
      ],
      "Provide the section, feedback focus, and your own diagnostic concern.",
      [
        "The section is identified.",
        "The feedback goal is explicit.",
        "The concern is specific.",
        "The passage has enough context.",
      ],
      "Evaluate whether the writing-feedback request is focused and answerable.",
    ),
    g(
      "Evaluate a particular presentation component after rehearsal or delivery.",
      [
        "Name the slide or section.",
        "Report timing and audience response if available.",
        "Identify a strength in narrative, figure, or delivery.",
        "Identify one concrete revision for clarity or timing.",
      ],
      "Describe the presentation component, evidence from rehearsal, and planned revision.",
      [
        "The component is identified.",
        "Evidence comes from rehearsal or delivery.",
        "Strength and weakness are specific.",
        "Revision is actionable.",
      ],
      "Evaluate specificity and usefulness of presentation feedback.",
    ),
    g(
      "Assess exam readiness by topic and task type.",
      [
        "Rate readiness for concepts, equations, calculations, and figure interpretation.",
        "Name the three weakest topics.",
        "Identify whether each weakness is knowledge or application.",
        "Set a revision and retest plan.",
      ],
      "Write the readiness ratings, weak topics, causes, and revision schedule.",
      [
        "Multiple task types are rated.",
        "Weaknesses are prioritized.",
        "Causes are diagnosed.",
        "Retesting is planned.",
      ],
      "Evaluate realism and actionability of exam-readiness reflection.",
    ),
    g(
      "Evaluate whether AI feedback improved your reasoning rather than merely rewriting text.",
      [
        "Identify the lesson or workspace where AI was used.",
        "State the original problem or uncertainty.",
        "Describe which AI suggestion was useful and why.",
        "Identify any suggestion that was unsupported, generic, or incorrect.",
      ],
      "Describe one AI interaction, the useful change it produced, and one limitation.",
      [
        "The context is identified.",
        "Usefulness is evidenced.",
        "AI limitations are considered.",
        "The final decision remains the student’s.",
      ],
      "Evaluate critical use of AI and evidence of learning.",
    ),
    g(
      "Identify concepts that remain unclear and formulate diagnostic questions.",
      [
        "Name the exact concept, equation, or interpretation step.",
        "State what you already understand.",
        "Locate the point where reasoning breaks down.",
        "Write one question that would resolve the uncertainty.",
      ],
      "For up to three concepts, write: known → unclear step → diagnostic question.",
      [
        "Concepts are specific.",
        "Existing understanding is stated.",
        "The breakdown point is located.",
        "Questions are answerable.",
      ],
      "Evaluate precision of the uncertainty diagnosis.",
    ),
    g(
      "Evaluate the course at the end using evidence from specific modules and activities.",
      [
        "Name the components that most supported learning.",
        "Identify content or activities that were redundant or unclear.",
        "Comment separately on lectures, practicals, assessments, workspaces, and AI.",
        "Recommend the three highest-priority changes.",
      ],
      "Write a structured course evaluation with examples and ranked recommendations.",
      [
        "Feedback covers distinct components.",
        "Examples support claims.",
        "Positive and negative feedback are balanced.",
        "Recommendations are prioritized.",
      ],
      "Evaluate evidence, balance, coverage, and priority of course-end feedback.",
    ),
    g(
      "Translate reflection into concrete next steps beyond the course.",
      [
        "Name the population-genetic skills you can now use independently.",
        "Identify one skill that still requires supervision.",
        "Choose a project, dataset, or advanced topic for continued practice.",
        "Set one measurable next action and date.",
      ],
      "Write your skill inventory and a concrete 30-day next-step plan.",
      [
        "Independent and developing skills are distinguished.",
        "The next activity is realistic.",
        "The action is measurable.",
        "A time point is specified.",
      ],
      "Evaluate realism, specificity, and continuity of the next-step plan.",
    ),
  ],
};
