


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."assign_new_user_to_population_genetics"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare c_id bigint; s_id bigint; is_uni boolean; domain text;
begin
 domain:=lower(split_part(new.email,'@',2));
 is_uni:=domain in ('uni-koeln.de','smail.uni-koeln.de','hhu.de','uni-duesseldorf.de');
 insert into public.profiles(user_id,display_name,institutional_user) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)),is_uni) on conflict(user_id) do nothing;
 select id into c_id from public.courses where slug='population-genetics';
 if is_uni then select id into s_id from public.semesters where course_id=c_id and status='active' order by start_date desc nulls last limit 1; else s_id:=null; end if;
 insert into public.course_members(course_id,user_id,semester_id,role) values(c_id,new.id,s_id,'student') on conflict(course_id,user_id) do update set semester_id=excluded.semester_id;
 return new;
end $$;


ALTER FUNCTION "public"."assign_new_user_to_population_genetics"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."conversation_turns" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "mode" "text" NOT NULL,
    "user_text" "text" NOT NULL,
    "ai_reply" "text" NOT NULL,
    "feedback" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."conversation_turns" OWNER TO "postgres";


ALTER TABLE "public"."conversation_turns" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."conversation_turns_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_members" (
    "course_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "semester_id" bigint,
    "role" "text" DEFAULT 'student'::"text" NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "course_members_role_check" CHECK (("role" = ANY (ARRAY['student'::"text", 'coordinator'::"text"])))
);


ALTER TABLE "public"."course_members" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."courses" (
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."courses" OWNER TO "postgres";


ALTER TABLE "public"."courses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."courses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."feedback_responses" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "context_type" "text" NOT NULL,
    "context_id" "text",
    "responses" "jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."feedback_responses" OWNER TO "postgres";


ALTER TABLE "public"."feedback_responses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_responses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."lesson_progress" (
    "user_id" "uuid" NOT NULL,
    "lesson_id" "text" NOT NULL,
    "completed" boolean DEFAULT false NOT NULL,
    "score" numeric,
    "attempts" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."lesson_progress" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" "uuid" NOT NULL,
    "display_name" "text",
    "account_type" "text" DEFAULT 'student'::"text" NOT NULL,
    "institutional_user" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "profiles_account_type_check" CHECK (("account_type" = ANY (ARRAY['student'::"text", 'coordinator'::"text", 'admin'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."project_workspaces" (
    "user_id" "uuid" NOT NULL,
    "current_stage" integer DEFAULT 1 NOT NULL,
    "draft" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."project_workspaces" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."semesters" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "status" "text" DEFAULT 'planned'::"text" NOT NULL,
    CONSTRAINT "semesters_status_check" CHECK (("status" = ANY (ARRAY['planned'::"text", 'active'::"text", 'closed'::"text"])))
);


ALTER TABLE "public"."semesters" OWNER TO "postgres";


ALTER TABLE "public"."semesters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."semesters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."conversation_turns"
    ADD CONSTRAINT "conversation_turns_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_members"
    ADD CONSTRAINT "course_members_pkey" PRIMARY KEY ("course_id", "user_id");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."feedback_responses"
    ADD CONSTRAINT "feedback_responses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."lesson_progress"
    ADD CONSTRAINT "lesson_progress_pkey" PRIMARY KEY ("user_id", "lesson_id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."project_workspaces"
    ADD CONSTRAINT "project_workspaces_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."semesters"
    ADD CONSTRAINT "semesters_course_id_name_key" UNIQUE ("course_id", "name");



ALTER TABLE ONLY "public"."semesters"
    ADD CONSTRAINT "semesters_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."conversation_turns"
    ADD CONSTRAINT "conversation_turns_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_members"
    ADD CONSTRAINT "course_members_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_members"
    ADD CONSTRAINT "course_members_semester_id_fkey" FOREIGN KEY ("semester_id") REFERENCES "public"."semesters"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."course_members"
    ADD CONSTRAINT "course_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."feedback_responses"
    ADD CONSTRAINT "feedback_responses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."lesson_progress"
    ADD CONSTRAINT "lesson_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_workspaces"
    ADD CONSTRAINT "project_workspaces_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."semesters"
    ADD CONSTRAINT "semesters_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("id") ON DELETE CASCADE;



ALTER TABLE "public"."conversation_turns" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feedback_responses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lesson_progress" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "own conversation" ON "public"."conversation_turns" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "own membership" ON "public"."course_members" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "own progress" ON "public"."lesson_progress" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "own project" ON "public"."project_workspaces" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_workspaces" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "submit feedback" ON "public"."feedback_responses" FOR INSERT WITH CHECK ((("auth"."uid"() = "user_id") OR ("user_id" IS NULL)));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."assign_new_user_to_population_genetics"() TO "anon";
GRANT ALL ON FUNCTION "public"."assign_new_user_to_population_genetics"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."assign_new_user_to_population_genetics"() TO "service_role";


















GRANT ALL ON TABLE "public"."conversation_turns" TO "anon";
GRANT ALL ON TABLE "public"."conversation_turns" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_turns" TO "service_role";



GRANT ALL ON SEQUENCE "public"."conversation_turns_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."conversation_turns_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."conversation_turns_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_members" TO "anon";
GRANT ALL ON TABLE "public"."course_members" TO "authenticated";
GRANT ALL ON TABLE "public"."course_members" TO "service_role";



GRANT ALL ON TABLE "public"."courses" TO "anon";
GRANT ALL ON TABLE "public"."courses" TO "authenticated";
GRANT ALL ON TABLE "public"."courses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."courses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."feedback_responses" TO "anon";
GRANT ALL ON TABLE "public"."feedback_responses" TO "authenticated";
GRANT ALL ON TABLE "public"."feedback_responses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feedback_responses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feedback_responses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feedback_responses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."lesson_progress" TO "anon";
GRANT ALL ON TABLE "public"."lesson_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."lesson_progress" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."project_workspaces" TO "anon";
GRANT ALL ON TABLE "public"."project_workspaces" TO "authenticated";
GRANT ALL ON TABLE "public"."project_workspaces" TO "service_role";



GRANT ALL ON TABLE "public"."semesters" TO "anon";
GRANT ALL ON TABLE "public"."semesters" TO "authenticated";
GRANT ALL ON TABLE "public"."semesters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."semesters_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created_population_genetics AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.assign_new_user_to_population_genetics();


